# Generated by Django 5.1.2 on 2024-10-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesForm_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=100)),
                ('productFeatures', models.TextField()),
                ('style', models.CharField(max_length=50)),
                ('wordCount', models.IntegerField()),
                ('otherRequirements', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
